[package]
name = "owx"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
owx-core.workspace = true
owx-vault.workspace = true
owx-pay.workspace = true

kobe.workspace = true
kobe-btc.workspace = true
kobe-cosmos.workspace = true
kobe-evm.workspace = true
kobe-fil.workspace = true
kobe-spark.workspace = true
kobe-sui.workspace = true
kobe-svm.workspace = true
kobe-ton.workspace = true
kobe-tron.workspace = true

signer.workspace = true
signer-btc.workspace = true
signer-cosmos.workspace = true
signer-evm.workspace = true
signer-fil.workspace = true
signer-spark.workspace = true
signer-sui.workspace = true
signer-svm.workspace = true
signer-ton.workspace = true
signer-tron.workspace = true

base64.workspace = true
chrono.workspace = true
getrandom.workspace = true
hex.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
uuid.workspace = true
zeroize.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
